### ISSUE TITLE
npm run generate doesnt create index_store.json

### ISSUE THREAD

**Issue by HardikJain02** [run-llama/voice-chat-pdf#1]
```
> openai-realtime-console@0.0.0 generate
> tsx src/pages/engine/generate.ts

Using 'openai' model provider
Generating storage context...
No valid data found at path: cache\index_store.json starting new store.
Storage context successfully generated in 0.519s.
Finished generating storage.
```

I am a window's user.

**Comment by marcusschiesser** [comment]
please try
pnpm tsx src\\pages\\engine\\generate.ts

**Comment by HardikJain02** [comment]
still same issue 
`pnpm tsx src\pages\engine\generate.ts
Using 'openai' model provider
Generating storage context...
No valid data found at path: cache\index_store.json starting new store.
Storage context successfully generated in 0.513s.
Finished generating storage.`

**Comment by amine7777** [comment]
Delete the cache folder 
Make sure the` OPENAI_API_KEY` is in the .env 
Run again the `npm run generate` command

**Comment by HardikJain02** [comment]
works, thanks.
